### ISSUE TITLE
активный пенкт меню 

### ISSUE THREAD

**Issue by cjbars** [Maryoku/Web-application#1]
Мне кажется проще выделить один пункт как активный, а не прописывать всем остальным пунктам НеАктивность
Вместо:
```

<ul class="menu__list">
            <li class="menu__item"><a class="link_disabled-decoration" href="/start.html">Start</a></li>
            <li class="menu__item"><a href="/about.html">About</a></li>
            <li class="menu__item"><a class="link_disabled-decoration" href="/toplist.html">Top List</a></li>
        </ul>
```
Сделать
```
<ul class="menu__list">
            <li class="menu__item"><a class="menu__link-active" href="/start.html">Start</a></li>
            <li class="menu__item"><a href="/about.html">About</a></li>
            <li class="menu__item"><a href="/toplist.html">Top List</a></li>
        </ul>
```

**Comment by Maryoku** [comment]
Там немножко не так, обозвала может немного неинтуитивно. Это класс который не помечает "неактивность", а со ссылочек подчеркивание и выделение убирает, чтобы они как простой текст выглядели. Т.е. это не для функционала меню, а именно для любых объектов типа "ссылка".
Для активного пункта меню у меня же там "menu__item_focused" висит. А "link_disabled-decoration" я еще на кнопке на странице старт юзаю. Не придумала как это лучше сделать, чтобы не прописывать такие модификаторы для каждого блока.

**Comment by cjbars** [comment]
если эти штуки нужны для большинства ссылок, то может задать всем ссылкам сразу это свойство. В особенным ссылкам приписывать особенные свойства.
м?

**Comment by Maryoku** [comment]
Типа всем тегам "a"? По БЭМУ же типо не хорошо так делать, css для тегов

**Comment by cjbars** [comment]
Ну ок, тогда сделайте класс menu__item-link и туда все стили для ссылки по умолчанию занесите

**Comment by cjbars** [comment]
Если вы решите вернуть подчеркивание, вам придется убирать ваш стиль со всех ссылок, а в моем варианте достаточно поправить лишь один стиль в css

**Comment by Maryoku** [comment]
fixed:
https://github.com/Maryoku/Web-application/commit/d5ddf69166f84f16fdf8a2c16b6a44bbf6bd817e
