### ISSUE TITLE
Спорный элемент массива

### ISSUE THREAD

**Issue by Maryoku** [Maryoku/Web-application#2]
В php классе получился такой костыль:
class Page {
    public static $items = array (
		0 => array( 'title' => '', 'link' => './assets/index.html'),

Кажется это не лучшее решение, т.к. пустая строка все равно оказывается элементом списка и сдвигает меню. Не знаю как это оптимизировать.

**Comment by cjbars** [comment]
У вас есть два метода использующих этот массив
1 - метод генерирующий меню
2 - метод генерирующий контент

для метода генерирующего контент ваш массив подходит хорошо
для метода генерирующего меню происходит нехорошее поведение

Вывод: 
- либо надо менять организацию массива, чтобы он подходил обоим методам (например сделать отдельное свойство класса отвечающее за ссылку на файл index, и доработать метод контента) 
- либо надо менять логику методов (например в методе меню исключать нулевой элемент)

PS бонус на то и бонус, чтобы содержать грабли, на которые можно наступить, вы наступили :-)

**Comment by Maryoku** [comment]
А если убрать нулевой элемент вообще и метод контента сделать так:

public static function getContent($item) {
    if (array_key_exists($item, self::$items)) {
      return file_get_contents(self::$items[$item]['link']);
    }
    else return file_get_contents('./assets/index.html');
}

**Comment by cjbars** [comment]
для лабы этого достаточно. 
Для более правильного пути тут нужно еще две вещи
1 - проверить а существует ли файл который вы читаете с через file_get_contents
2 - заменить ```file_get_contents('./assets/index.html'); ``` на ``` file_get_contents(DEFAULT_CONTENT_FILE);``` и константу DEFAULT_CONTENT_FILE задать гдето в начале, например в index.php
так вы сможете менять логику приложения не меняя его код

**Comment by Maryoku** [comment]
Так вот же проверка на существование:
if (array_key_exists($item, self::$items))

**Comment by cjbars** [comment]
Это проверка на существование ключа в массиве
затем вы делаете file_get_contents, который открывает файл, но файла может не быть, либо в массиве может содержаться ошибочный путь

**Comment by Maryoku** [comment]
fixed?
855a08b2e4a874035976b8706fa4d908594850e1

**Comment by cjbars** [comment]
fixed, закрывайте
